#!/bin/bash
# Amazon Connect Integration - Complete Setup

INSTANCE_ID="a88ddab9-3b29-409f-87f0-bdb614abafef"
PHONE_NUMBER="+18332896602"
PHONE_ID="c3f388bc-0eeb-489a-b7d5-916758416f4a"

echo "=========================================="
echo "Amazon Connect Integration Status"
echo "=========================================="
echo ""

echo "✅ Phone Number Claimed: $PHONE_NUMBER"
echo "✅ Lambda Permissions: Granted for all 5 AgentCore runtimes"
echo "✅ Contact Lens: Enabled"
echo "✅ Kinesis Stream: Associated"
echo ""

echo "=========================================="
echo "NEXT STEPS - Manual Configuration Required"
echo "=========================================="
echo ""
echo "The Connect contact flow designer requires manual configuration."
echo "Follow these steps in the AWS Console:"
echo ""
echo "1. Open Amazon Connect Console:"
echo "   https://console.aws.amazon.com/connect/v2/app/instances"
echo ""
echo "2. Click on 'treasury-connect-prod' instance"
echo ""
echo "3. Click 'Log in for emergency access' or set up admin user"
echo ""
echo "4. In Connect admin panel, go to:"
echo "   Routing → Contact flows → Create contact flow"
echo ""
echo "5. Build the flow with these blocks:"
echo "   a) Play prompt: 'Welcome to U.S. Treasury. Press 1 for IRS, 2 for U.S. Mint, 3 for Bureau of Fiscal Service, 4 for Treasury Direct, 5 for Direct Express.'"
echo "   b) Get customer input: Store as 'BureauSelection'"
echo "   c) Check contact attributes: Branch on BureauSelection value"
echo "   d) Invoke AWS Lambda function:"
echo "      - For option 1: TreasuryAgentCoreStack-AgentIRSRuntimeEF528323-jDt5qsNk3hyR"
echo "      - For option 2: TreasuryAgentCoreStack-AgentMINTRuntime14C8D456-SBKYsYEZF0Eg"
echo "      - For option 3: TreasuryAgentCoreStack-AgentTOPRuntime071D2934-HPN9JTUkogG9"
echo "      - For option 4: TreasuryAgentCoreStack-AgentTDRuntimeA5106084-C1YR5ulT2wLJ"
echo "      - For option 5: TreasuryAgentCoreStack-AgentDERuntime778B6C5C-IADf7Pmqvk32"
echo "   e) Play prompt: Use Lambda response ($.External.response)"
echo "   f) Disconnect"
echo ""
echo "6. Save and publish the flow as 'Treasury Main Flow'"
echo ""
echo "7. Associate phone number with flow:"
echo "   Channels → Phone numbers → $PHONE_NUMBER"
echo "   Set Contact flow to 'Treasury Main Flow'"
echo ""
echo "8. Test by calling: $PHONE_NUMBER"
echo ""

echo "=========================================="
echo "Alternative: Use Sample Flow for Quick Test"
echo "=========================================="
echo ""
echo "For immediate testing:"
echo "1. Go to Routing → Contact flows"
echo "2. Find 'Sample inbound flow (first contact experience)'"
echo "3. Edit it and add an 'Invoke AWS Lambda function' block"
echo "4. Select: TreasuryAgentCoreStack-AgentIRSRuntimeEF528323-jDt5qsNk3hyR"
echo "5. Save and publish"
echo "6. Associate $PHONE_NUMBER with this flow"
echo "7. Call to test"
echo ""

echo "=========================================="
echo "Testing Backend (Works Now)"
echo "=========================================="
echo ""
echo "While setting up Connect, test the backend:"
echo ""
echo "# Test AI agents directly"
echo "python3 test-connect-agentcore.py"
echo ""
echo "# Launch UI dashboard"
echo "npm start"
echo ""
echo "# Test Lambda function"
echo "aws lambda invoke --function-name TreasuryAgentCoreStack-AgentIRSRuntimeEF528323-jDt5qsNk3hyR \\"
echo "  --payload '{\"message\":\"Where is my refund?\",\"bureau\":\"IRS\"}' \\"
echo "  response.json && cat response.json"
echo ""

echo "=========================================="
echo "Resources"
echo "=========================================="
echo ""
echo "Instance ID: $INSTANCE_ID"
echo "Phone Number: $PHONE_NUMBER"
echo "Phone ID: $PHONE_ID"
echo "Region: us-east-1"
echo ""
echo "Lambda Functions:"
echo "  - IRS:  TreasuryAgentCoreStack-AgentIRSRuntimeEF528323-jDt5qsNk3hyR"
echo "  - MINT: TreasuryAgentCoreStack-AgentMINTRuntime14C8D456-SBKYsYEZF0Eg"
echo "  - TOP:  TreasuryAgentCoreStack-AgentTOPRuntime071D2934-HPN9JTUkogG9"
echo "  - TD:   TreasuryAgentCoreStack-AgentTDRuntimeA5106084-C1YR5ulT2wLJ"
echo "  - DE:   TreasuryAgentCoreStack-AgentDERuntime778B6C5C-IADf7Pmqvk32"
echo ""
echo "Documentation:"
echo "  - AMAZON_CONNECT_TEST_PLAN.md"
echo "  - TESTING_STATUS.md"
echo "  - EXECUTIVE_SUMMARY.md"
echo ""
