#!/bin/bash

echo "=========================================="
echo "🎯 CXAI AMAZON CONNECT - READY FOR TESTING"
echo "=========================================="
echo ""
echo "✅ Phone Number: +1 (833) 289-6602"
echo "✅ Contact Flow: TreasuryAgentCoreFlow"
echo "✅ Lambda: IRS AgentCore Runtime"
echo "✅ Status: LIVE and ready to receive calls"
echo ""
echo "=========================================="
echo "📞 HOW TO TEST"
echo "=========================================="
echo ""
echo "1. Call the number: +1 (833) 289-6602"
echo "2. Listen to the greeting message"
echo "3. The IRS AI agent will respond"
echo "4. Check logs and DynamoDB for results"
echo ""
echo "=========================================="
echo "🔍 MONITORING OPTIONS"
echo "=========================================="
echo ""
echo "Option 1: Watch Lambda logs in real-time"
echo "  aws logs tail /aws/lambda/TreasuryAgentCoreStack-AgentIRSRuntimeEF528323-jDt5qsNk3hyR --follow"
echo ""
echo "Option 2: Check DynamoDB for contact records"
echo "  aws dynamodb scan --table-name TreasuryContacts --limit 5"
echo ""
echo "Option 3: View Connect contact records"
echo "  aws connect search-contacts --instance-id a88ddab9-3b29-409f-87f0-bdb614abafef --time-range Type=INITIATION_TIMESTAMP,StartTime=2026-03-02T00:00:00Z,EndTime=2026-03-03T00:00:00Z"
echo ""
echo "=========================================="
echo "🧪 BACKEND TEST (Without Phone)"
echo "=========================================="
echo ""
echo "Test the Lambda directly:"
echo "  python3 test-connect-agentcore.py"
echo ""
echo "=========================================="
echo "📊 SYSTEM STATUS"
echo "=========================================="
echo ""

# Check Lambda function
echo -n "Lambda Function: "
aws lambda get-function --function-name TreasuryAgentCoreStack-AgentIRSRuntimeEF528323-jDt5qsNk3hyR --query 'Configuration.State' --output text 2>/dev/null || echo "ERROR"

# Check phone number
echo -n "Phone Number: "
aws connect describe-phone-number --phone-number-id c3f388bc-0eeb-489a-b7d5-916758416f4a --query 'ClaimedPhoneNumberSummary.PhoneNumberStatus.Status' --output text 2>/dev/null || echo "ERROR"

# Check contact flow
echo -n "Contact Flow: "
aws connect describe-contact-flow --instance-id a88ddab9-3b29-409f-87f0-bdb614abafef --contact-flow-id 27e3aaec-09ca-40d1-8101-90b1b921712e --query 'ContactFlow.Status' --output text 2>/dev/null || echo "ERROR"

echo ""
echo "=========================================="
echo "✅ SYSTEM IS LIVE - MAKE YOUR CALL!"
echo "=========================================="
